///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MobileTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MobileTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("16ed4bfa-0fd4-448e-bf1b-4517e2fbd850")]
    public partial class MobileTestRepository : RepoGenBaseFolder
    {
        static MobileTestRepository instance = new MobileTestRepository();

        /// <summary>
        /// Gets the singleton class instance representing the MobileTestRepository element repository.
        /// </summary>
        [RepositoryFolder("16ed4bfa-0fd4-448e-bf1b-4517e2fbd850")]
        public static MobileTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MobileTestRepository() 
            : base("MobileTestRepository", "/", null, 0, false, "16ed4bfa-0fd4-448e-bf1b-4517e2fbd850", ".\\RepositoryImages\\MobileTestRepository16ed4bfa.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("16ed4bfa-0fd4-448e-bf1b-4517e2fbd850")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MobileTestRepositoryFolders
    {
    }
#pragma warning restore 0436
}
