///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Amazon
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the AmazonRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("c42d542c-2f70-4569-a6cf-8e95139db0b5")]
    public partial class AmazonRepository : RepoGenBaseFolder
    {
        static AmazonRepository instance = new AmazonRepository();
        AmazonRepositoryFolders.AmazonAppFolder _amazon;

        /// <summary>
        /// Gets the singleton class instance representing the AmazonRepository element repository.
        /// </summary>
        [RepositoryFolder("c42d542c-2f70-4569-a6cf-8e95139db0b5")]
        public static AmazonRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public AmazonRepository() 
            : base("AmazonRepository", "/", null, 0, false, "c42d542c-2f70-4569-a6cf-8e95139db0b5", ".\\RepositoryImages\\AmazonRepositoryc42d542c.rximgres")
        {
            _amazon = new AmazonRepositoryFolders.AmazonAppFolder(this);
        }

#region Variables

        string _rep_ItemName = "Fenoix Men's Cotton T-Shirt Hooded Maroon-Medium\n";

        /// <summary>
        /// Gets or sets the value of variable rep_ItemName.
        /// </summary>
        [TestVariable("17d583bd-ed82-419b-843c-8efa1b6b6772")]
        public string rep_ItemName
        {
            get { return _rep_ItemName; }
            set { _rep_ItemName = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c42d542c-2f70-4569-a6cf-8e95139db0b5")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Amazon folder.
        /// </summary>
        [RepositoryFolder("fb4964e0-de80-431e-b9c4-84b16b488572")]
        public virtual AmazonRepositoryFolders.AmazonAppFolder Amazon
        {
            get { return _amazon; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class AmazonRepositoryFolders
    {
        /// <summary>
        /// The AmazonAppFolder folder.
        /// </summary>
        [RepositoryFolder("fb4964e0-de80-431e-b9c4-84b16b488572")]
        public partial class AmazonAppFolder : RepoGenBaseFolder
        {
            AmazonRepositoryFolders.HeaderFolder _header;
            AmazonRepositoryFolders.BodyFolder _body;

            /// <summary>
            /// Creates a new Amazon  folder.
            /// </summary>
            public AmazonAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Amazon", "/dom[@domain='www.amazon.in']", parentFolder, 30000, null, false, "fb4964e0-de80-431e-b9c4-84b16b488572", "")
            {
                _header = new AmazonRepositoryFolders.HeaderFolder(this);
                _body = new AmazonRepositoryFolders.BodyFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fb4964e0-de80-431e-b9c4-84b16b488572")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fb4964e0-de80-431e-b9c4-84b16b488572")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Header folder.
            /// </summary>
            [RepositoryFolder("538c18a1-a444-4333-95fe-0875cbfd3b9b")]
            public virtual AmazonRepositoryFolders.HeaderFolder Header
            {
                get { return _header; }
            }

            /// <summary>
            /// The Body folder.
            /// </summary>
            [RepositoryFolder("cf0888c5-491e-4933-8727-4ceada3e5b64")]
            public virtual AmazonRepositoryFolders.BodyFolder Body
            {
                get { return _body; }
            }
        }

        /// <summary>
        /// The HeaderFolder folder.
        /// </summary>
        [RepositoryFolder("538c18a1-a444-4333-95fe-0875cbfd3b9b")]
        public partial class HeaderFolder : RepoGenBaseFolder
        {
            RepoItemInfo _cartInfo;

            /// <summary>
            /// Creates a new Header  folder.
            /// </summary>
            public HeaderFolder(RepoGenBaseFolder parentFolder) :
                    base("Header", ".//header[@tagname='header']", parentFolder, 30000, null, false, "538c18a1-a444-4333-95fe-0875cbfd3b9b", "")
            {
                _cartInfo = new RepoItemInfo(this, "Cart", ".//a[@id~'cart']", 30000, null, "a41c897e-fccc-406d-8d3e-3080be07a93c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("538c18a1-a444-4333-95fe-0875cbfd3b9b")]
            public virtual Ranorex.HeaderTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.HeaderTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("538c18a1-a444-4333-95fe-0875cbfd3b9b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Cart item.
            /// </summary>
            [RepositoryItem("a41c897e-fccc-406d-8d3e-3080be07a93c")]
            public virtual Ranorex.ATag Cart
            {
                get
                {
                    return _cartInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Cart item info.
            /// </summary>
            [RepositoryItemInfo("a41c897e-fccc-406d-8d3e-3080be07a93c")]
            public virtual RepoItemInfo CartInfo
            {
                get
                {
                    return _cartInfo;
                }
            }
        }

        /// <summary>
        /// The BodyFolder folder.
        /// </summary>
        [RepositoryFolder("cf0888c5-491e-4933-8727-4ceada3e5b64")]
        public partial class BodyFolder : RepoGenBaseFolder
        {
            AmazonRepositoryFolders.CartViewFolder _cartview;

            /// <summary>
            /// Creates a new Body  folder.
            /// </summary>
            public BodyFolder(RepoGenBaseFolder parentFolder) :
                    base("Body", ".//div[@id~'content']", parentFolder, 30000, null, false, "cf0888c5-491e-4933-8727-4ceada3e5b64", "")
            {
                _cartview = new AmazonRepositoryFolders.CartViewFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cf0888c5-491e-4933-8727-4ceada3e5b64")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cf0888c5-491e-4933-8727-4ceada3e5b64")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CartView folder.
            /// </summary>
            [RepositoryFolder("4e492c84-5c9a-40d4-b4dd-a2c67c4a9802")]
            public virtual AmazonRepositoryFolders.CartViewFolder CartView
            {
                get { return _cartview; }
            }
        }

        /// <summary>
        /// The CartViewFolder folder.
        /// </summary>
        [RepositoryFolder("4e492c84-5c9a-40d4-b4dd-a2c67c4a9802")]
        public partial class CartViewFolder : RepoGenBaseFolder
        {
            RepoItemInfo _itemInfo;

            /// <summary>
            /// Creates a new CartView  folder.
            /// </summary>
            public CartViewFolder(RepoGenBaseFolder parentFolder) :
                    base("CartView", ".//form[@id='activeCartViewForm']", parentFolder, 30000, null, false, "4e492c84-5c9a-40d4-b4dd-a2c67c4a9802", "")
            {
                _itemInfo = new RepoItemInfo(this, "Item", ".//span[@innertext~$rep_ItemName and @visible='True']", 30000, null, "9d3a68dc-bd42-471b-aaf3-77533672dfa9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4e492c84-5c9a-40d4-b4dd-a2c67c4a9802")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4e492c84-5c9a-40d4-b4dd-a2c67c4a9802")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Item item.
            /// </summary>
            [RepositoryItem("9d3a68dc-bd42-471b-aaf3-77533672dfa9")]
            public virtual Ranorex.SpanTag Item
            {
                get
                {
                    return _itemInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Item item info.
            /// </summary>
            [RepositoryItemInfo("9d3a68dc-bd42-471b-aaf3-77533672dfa9")]
            public virtual RepoItemInfo ItemInfo
            {
                get
                {
                    return _itemInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
