///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Amazon
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the AmazonRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("c42d542c-2f70-4569-a6cf-8e95139db0b5")]
    public partial class AmazonRepository : RepoGenBaseFolder
    {
        static AmazonRepository instance = new AmazonRepository();
        AmazonRepositoryFolders.AmazonAppFolder _amazon;

        /// <summary>
        /// Gets the singleton class instance representing the AmazonRepository element repository.
        /// </summary>
        [RepositoryFolder("c42d542c-2f70-4569-a6cf-8e95139db0b5")]
        public static AmazonRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public AmazonRepository() 
            : base("AmazonRepository", "/", null, 0, false, "c42d542c-2f70-4569-a6cf-8e95139db0b5", ".\\RepositoryImages\\AmazonRepositoryc42d542c.rximgres")
        {
            _amazon = new AmazonRepositoryFolders.AmazonAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c42d542c-2f70-4569-a6cf-8e95139db0b5")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Amazon folder.
        /// </summary>
        [RepositoryFolder("fb4964e0-de80-431e-b9c4-84b16b488572")]
        public virtual AmazonRepositoryFolders.AmazonAppFolder Amazon
        {
            get { return _amazon; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class AmazonRepositoryFolders
    {
        /// <summary>
        /// The AmazonAppFolder folder.
        /// </summary>
        [RepositoryFolder("fb4964e0-de80-431e-b9c4-84b16b488572")]
        public partial class AmazonAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Amazon  folder.
            /// </summary>
            public AmazonAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Amazon", "/dom[@domain='www.amazon.in']", parentFolder, 30000, null, false, "fb4964e0-de80-431e-b9c4-84b16b488572", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fb4964e0-de80-431e-b9c4-84b16b488572")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fb4964e0-de80-431e-b9c4-84b16b488572")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
